### PR TITLE
Builder addon command

### PR DESCRIPTION
**Pull request by rmpestano**
- added builder command
- added builder command test
- renamed instance field 'obj' to class name

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi George,

don't know if there are plans to create addons (or they already exist) for this project, in any case here is some code

**Comment by gastaldi** [comment]
Hello Rafael,

Thank you for the PR. I think it would be nice to have these in the https://github.com/forge/core/tree/master/dev-tools-java addon. I also have https://github.com/forge/roaster/pull/42 to have this added to Roaster, so it would be available without much fuzz.

**Comment by rmpestano** [comment]
great, so Design patterns goes into roaster and design pattern addons into dev-tools, right?

**Comment by gastaldi** [comment]
Yes, that's the initial thought. Open for ideas

**Comment by rmpestano** [comment]
thats ok, I'll close this PR then

**Comment by gastaldi** [comment]
:+1: Thank you

**Comment by rmpestano** [comment]
you're welcome!

**Comment by rmpestano** [comment]
A small questions, I was not able to test a validation error, the test gives me timeout exception and I cannot inspect command Result, how you test that? 
ex: https://github.com/rmpestano/design-patterns/blob/master/src/test/java/org/jboss/forge/builder/BuilderAddonTest.java#L90

**Comment by gastaldi** [comment]
The timeout exception might have the STDOUT and STDERR from the command
displayed in the stacktract. That's where you can see what's wrong in the
command execution

On Wed, Sep 23, 2015 at 4:12 PM, Rafael M. Pestano <notifications@github.com
> wrote:

> A small questions, I was not able to test a validation error, the test
> gives me timeout exception and I cannot inspect command Result, how you
> test that?
> ex:
> https://github.com/rmpestano/design-patterns/blob/master/src/test/java/org/jboss/forge/builder/BuilderAddonTest.java#L90
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gastaldi/design-patterns/pull/1#issuecomment-142700920>
> .
>



-- 
*George Gastaldi | Senior Software Engineer*

JBoss Forge Team
T: +55 11 3524-6169
M: +55 47 9711-1000

**Comment by rmpestano** [comment]
right, used ex.getMessage().contains("The selected file must be Java file")

**Pull request closed without merging**
